version: '3'

services:
  mysql:
    build:
      context: ./
      dockerfile: Dockerfile.mysql
    ports:
      - 3306:3306
      - 33306:33306

  postgresql:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: "test_user_password"
    volumes:
    - ./pg_init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
